### ISSUE TITLE
Get gene embedding for gene similarity using anc2vec

### ISSUE THREAD

**Issue by hoangthienan95** [aedera/anc2vec#1]
Hi there,

Thank you for the really interesting paper and model. I'm working through the paper and repo, so I apologize if the answer to my question is really obvious and I have missed it. I have a custom gene-to-GO annotations. How can I use anc2vec to get an embedding of genes based on their GO annotation to do analysis on gene similarity based on GO annotations? Which resource should I look at first?

Thank you!

**Comment by aedera** [comment]
Hello,

You could have a look to this [Jupyter notebook](https://colab.research.google.com/github/aedera/anc2vec/blob/main/examples/pretrained_anc2vec_embeddings.ipynb). It shows how to obtain the anc2vec embedding for a given GO term. To represent a gene as an embedding, first obtain the embeddings from its GO annotations, and then combined them into a single embedding, for example, by summing them:

```
import anc2vec

embeds = anc2vec.get_embeddings()

# let's assume a gene with two GO annotations
e1 = embeds['GO:0044423'] 
e2 = embeds['GO:0032991'] 

gene_embedding = e1 + e2
```


Best,

**Comment by hoangthienan95** [comment]
Thank you. With your testing, is summing the GO embeddings the best way to get gene embedding? It's probably problem-specific but curious to know if you think a more complex way would be better

**Comment by aedera** [comment]
The embeddings built by anc2vec are designed to be combined by using the sum. This is due to the decomposability property explained in the [article](https://raw.githubusercontent.com/aedera/anc2vec/main/ms.pdf). I am not sure if more complex forms of combining embeddings would be better.
